/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rajat.practice;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.util.Scanner;
import javax.swing.SwingUtilities;

/**
 *
 * @author i_rajat_1
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form TextEntered
     */
    public MainFrame() {
        super("TEXTBURST");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextLable = new javax.swing.JLabel();
        EnterText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        txtCount = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        Cancelbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextLable.setForeground(new java.awt.Color(230, 188, 105));
        TextLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextLable.setText("TEXT BURST");
        getContentPane().add(TextLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 40));

        EnterText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnterText.setForeground(new java.awt.Color(230, 188, 105));
        EnterText.setText("Enter Your Text");
        getContentPane().add(EnterText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 188, 105));
        jLabel1.setText("How Many Times You Want To Print Your Message");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 420, 30));

        txtMessage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });
        getContentPane().add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 420, -1));
        getContentPane().add(txtCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 420, -1));

        btnStart.setBackground(new java.awt.Color(0, 51, 51));
        btnStart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStart.setForeground(new java.awt.Color(230, 188, 105));
        btnStart.setText("SUBMIT");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 190, -1));

        Cancelbtn.setBackground(new java.awt.Color(0, 51, 51));
        Cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cancelbtn.setForeground(new java.awt.Color(230, 188, 105));
        Cancelbtn.setText("CANCEL");
        Cancelbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\i_rajat_1\\Pictures\\DownloadPics\\mars1.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    private void CancelbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelbtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelbtnMouseClicked

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        // TODO add your handling code here :         
    }//GEN-LAST:event_btnStartMouseClicked

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        String msg = txtMessage.getText().trim();
        String countStr = txtCount.getText().trim();

    if (msg.isEmpty() || countStr.isEmpty()) {
        lblStatus.setText("Please fill both fields!");
        return;
    }

    int count;
    try {
        count = Integer.parseInt(countStr);
    } catch (NumberFormatException e) {
        lblStatus.setText("Enter a valid number!");
        return;
    }

    lblStatus.setText("You have 5 seconds to focus the chat window...");
    
    // Run automation in a new thread to avoid GUI freezing
    new Thread(() -> {
        try {
            Thread.sleep(5000);

            // Set text to clipboard
            StringSelection stringSelection = new StringSelection(msg);
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            clipboard.setContents(stringSelection, null);

            Robot robot = new Robot();
            for (int i = 0; i < count; i++) {
                // Paste
                robot.keyPress(KeyEvent.VK_CONTROL);
                robot.keyPress(KeyEvent.VK_V);
                robot.keyRelease(KeyEvent.VK_V);
                robot.keyRelease(KeyEvent.VK_CONTROL);

                // Enter
                robot.keyPress(KeyEvent.VK_ENTER);
                robot.keyRelease(KeyEvent.VK_ENTER);

                Thread.sleep(1000);
            }

            SwingUtilities.invokeLater(() -> lblStatus.setText("Done!"));
        } catch (Exception e) {
            SwingUtilities.invokeLater(() -> lblStatus.setText("Error: " + e.getMessage()));
        }
    }).start();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JLabel EnterText;
    private javax.swing.JLabel TextLable;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCount;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables

}
